### ISSUE TITLE
Add 'drain'-event

### ISSUE THREAD

**Issue by VanCoding** [maxogden/websocket-stream#1]
Is it possible to add the 'drain'-event?

I looked at the WebSocket specification and there is no such event and I'm not sure if there's a way to do it. But it would be great!

Maybe, you have any idea on how to implement it...

**Comment by jnordberg** [comment]
I'm using this patched socketWriteBrowser function to do this:

```javascript
function socketWriteBrowser(chunk, enc, next) {

  if (socket.bufferedAmount > 16384) {
    setTimeout(function(){
      socketWriteBrowser(chunk, enc, next)
    }, 10)
    return
  }

  try {
    socket.send(chunk)
  } catch(err) {
    return next(err)
  }

  next()
}
```

Not sure if this is the best way to go about this but it's been working well so far. With this patch I can upload large (>1gb) files over websockets without chrome eating all memory and cpu.

**Comment by mcollina** [comment]
@jnordberg I think we should avoid to allocate a closure, it would give us more speed :). Something like:

```js
function socketWriteBrowser(chunk, enc, next) {

  if (socket.bufferedAmount > 16384) {
    return setTimeout(socketWriteBrowser, 10, chunk, enc, next)
  }

  try {
    socket.send(chunk)
  } catch(err) {
    return next(err)
  }

  next()
}
```

I'm :+1: on this. PR?

**Comment by jnordberg** [comment]
Neat, I didn't know you could pass along arguments to setTimeout.

I'll prepare a PR
