### ISSUE TITLE
Insecure Randomness in ws 1.x

### ISSUE THREAD

**Issue by marvinroger** [maxogden/websocket-stream#105]
See https://snyk.io/vuln/npm:ws:20160920

Solution: Update to v2.x

**Comment by antoniobusrod** [comment]
Or update to https://github.com/websockets/ws/releases/tag/1.1.2 if you want to stay at v1

**Comment by mcollina** [comment]
It's already picking it, closing https://github.com/maxogden/websocket-stream/blob/master/package.json#L29.

**Comment by antoniobusrod** [comment]
However, this update will be installed automatically from minor release update in `ws@1.1.2`. I don't know if this a issue in **snyk**, because it should be solved after update `node_modules`.

**Comment by mcollina** [comment]
Yes it's a problem with snyk, 1.1.2 is safe to use.
