### ISSUE TITLE
Multiple Duplex Streams per Connection?

### ISSUE THREAD

**Issue by simplygreatwork** [maxogden/websocket-stream#107]
I'm currently evaluating using websocket-stream. One of the nicer aspects of using socket.io is that you can return a response back to any emitter - and it gets routed back to that callback handler. Does websocket-stream support multiple duplex streams (channels) per connection? If not, what's the best approach?

**Comment by mcollina** [comment]
You can use http://npm.im/multiplex or http://npm.im/tentacoli on top.
