### ISSUE TITLE
require('ws').Server causes undefined error on client

### ISSUE THREAD

**Issue by alexleonescalera** [maxogden/websocket-stream#113]
I'm using this library with React Native via aws-iot-device-sdk. React Native uses browser WebSockets, therefore it is going for the `ws-fallback.js` instead of the `ws` package.

https://github.com/maxogden/websocket-stream/blob/master/server.js#L3 is failing since the browser WebSocket object doesn't have a `Server` property.

**Comment by mcollina** [comment]
I do not think `'ws'` can run on react-native. You should check with them.

cc @lpinca.

**Comment by lpinca** [comment]
> React Native uses browser WebSockets

Yes, in this case you should use the native WebSocket object which obviously doesn't work as a server.

**Comment by alexleonescalera** [comment]
Thanks for the feedback. I was thinking more between the lines of conditionally include the server code inside the index.js. Something like:

```javascript
module.exports = require('./stream.js')

if (WebSockets) {
  var Server = require('./server.js')
  module.exports.Server = Server 
  module.exports.createServer = Server
}
```

**Comment by mcollina** [comment]
because of [this line](https://github.com/maxogden/websocket-stream/blob/master/package.json#L41) this should be done by your bundler. We may need some special directives for react-native., something like: https://github.com/nodejs/readable-stream/blob/master/package.json#L44.
Would you mind firing up a PR that address this issue?

**Comment by alexleonescalera** [comment]
Sure, I'll look into it and send a PR. Thanks for the info.

**Comment by alexleonescalera** [comment]
FYI: opened an issue on React Native:
https://github.com/facebook/react-native/issues/13474
