### ISSUE TITLE
[Question] Why there is "xterm" in the name of this code ? Does it fit well with xterm.js ?

### ISSUE THREAD

**Issue by JeromeVi** [maxogden/websocket-stream#118]
Hi,
I'm working with [Xterm.js](https://github.com/sourcelair/xterm.js) but at this moment I have some troubles to open X terminals with X streams. 

So I typed : xterm multiple streams on Google and I got https://www.npmjs.com/package/websocket-stream-xterm who is your code. Then I searched into it but I can't find any xterm things...

So could you help me to understand that ? 

Thank you

**Comment by mcollina** [comment]
We do not maintain that package. I am not sure why it points here.

**Comment by JeromeVi** [comment]
Okay so it's nice to know. Have a nice day
