### ISSUE TITLE
Sometimes takes very long time to connect

### ISSUE THREAD

**Issue by binarykitchen** [maxogden/websocket-stream#122]
With your latest code and nginx 1.10 inbetween, it can happen that the `onopen` event handling is triggered after one min (!)

Any reasons what this could be? Hints welcome so that I can investigate deeper ...

**Comment by mcollina** [comment]
no idea. Maybe you should ask to some nginx folks as well.

**Comment by binarykitchen** [comment]
i think the problem is deeper. when i use `wscat` in command line to see how responsive a websocket is, then it always responds. must be something else.

not sure if this is related but didn't happen before i switched to `objectMode: true`

**Comment by binarykitchen** [comment]
not happening anymore, changing objectMode did the trick
