### ISSUE TITLE
Add TypeScript definitions?

### ISSUE THREAD

**Issue by AppLover69** [maxogden/websocket-stream#144]
Could be done here in an `index.d.ts` file (doesn't require installing another package) or in https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by mcollina** [comment]
would you like to send a PR?

Il giorno dom 4 nov 2018 alle 09:01 AppLover69 <notifications@github.com>
ha scritto:

**Comment by benjamincburns** [comment]
#150 submitted to address this.
