### ISSUE TITLE
v5.2.0 is breaking ... can't say exactly what

### ISSUE THREAD

**Issue by binarykitchen** [maxogden/websocket-stream#148]
This with your latest v5.2.0 breaking my www.videomail.io app - had to revert back to 5.1.2

Afraid I can't exactly say what it is.

**Comment by binarykitchen** [comment]
If it helps, objectMode is set to true here

**Comment by mcollina** [comment]
Reverted in v5.3.0.

@scarry1992 can you please send the PR again?

**Comment by scarry1992** [comment]
@mcollina, I remove my fork already. What going on?

**Comment by mcollina** [comment]
It seems your changes are breaking @binarykitchen.

**Comment by scarry1992** [comment]
ok then, I remake PR. But what case breaks my changes?

**Comment by scarry1992** [comment]
@mcollina, https://github.com/maxogden/websocket-stream/pull/149. Ok?

**Comment by binarykitchen** [comment]
sorry guys, been busy. trying to give you more information here to reproduce:
1. git clone https://github.com/binarykitchen/videomail-client
2. run example with `yarn start`, all works fine
3. bump websocket-stream dependency to 5.2.0
4. try one example again, it fails, behaves differently (always connecting)

i've also opened console and can see a different sequence of events emitted

before (when it worked) it was
1. resume, 2. uncork, 3. connect and then 4. data
<img width="662" alt="Screen Shot 2019-03-28 at 16 59 19" src="https://user-images.githubusercontent.com/177641/55129282-5cb98480-517b-11e9-8d11-b786e38667b6.png">

but after, with v5.2.0 it is
1. resume, 2. connect and 3. preend (ends too early?)
<img width="678" alt="Screen Shot 2019-03-28 at 16 57 47" src="https://user-images.githubusercontent.com/177641/55129283-617e3880-517b-11e9-87d1-8bc6f3773d5e.png">

afraid cant tell more. but feel free to use this repo to reproduce the problem.

**Comment by nuhamind2** [comment]
I am getting bunch of `self is undefined` and `state is undefined` using 5.30, work OK with 5.12

**Comment by AlexStacker** [comment]
After upgrading to 5.3.0, the version number of the `readable-stream` library used is 3.0, which makes mqtt not work properly. It seems that the `process-nextick-args` is removed. Can it be solved as soon as possible?

**Comment by AlexStacker** [comment]
By setting the webpack node environment variable is already ok
![QQ截图20190403170625](https://user-images.githubusercontent.com/7822744/55467132-3c823d80-5633-11e9-9bcb-6990a4175153.png)

**Comment by mcollina** [comment]
Should be fixed in 5.4.0
