### ISSUE TITLE
Trying to get a simple echo server to work.

### ISSUE THREAD

**Issue by madtechsupport** [maxogden/websocket-stream#52]
Hi,

Apologies if this is not the correct place to be asking this question. I'm trying to get a simple echo example to work and I don't understand why the below code doesn't work?

    var WebSocketServer = require('ws').Server
    var websocket = require('websocket-stream')
    var wss = new WebSocketServer({port: 8000})
    wss.on('connection', function(ws) {
      var stream = websocket(ws)
      stream.pipe(stream)
    })

Thanks,
Warren.

**Comment by mcollina** [comment]
`WebSocketServer` do not accept a `port` option, but requires a `server`, which must be an http/https server.

Here is an example: https://github.com/maxogden/websocket-stream/blob/master/echo-server.js#L20-L31
