### ISSUE TITLE
How can I set a custom header?

### ISSUE THREAD

**Issue by binarykitchen** [maxogden/websocket-stream#66]
On the client side, in the `websocket()` constructor, how can I set a custom header there? I need this for an API ...

**Comment by maxogden** [comment]
you can pass in your own `WebSocket` instance as the first argument, so just use the browsers builtin `new WebSocket` and do whatever you want https://github.com/maxogden/websocket-stream/blob/master/stream.js#L12

**Comment by binarykitchen** [comment]
Yes, I could do that. But the disadvantage is that I have to add `ws` as a new dependency into my project. I want to avoid this.

Why not have a third parameters `headers` in the constructor and pass this? See here
https://github.com/theturtle32/WebSocket-Node/pull/58/files

**Comment by binarykitchen** [comment]
@maxogden Also you'll risk that versions of WS do not match when you add ws as an external dependency. Not so good I think.

**Comment by binarykitchen** [comment]
@maxogden @mcollina Would you accept a PR?

**Comment by mcollina** [comment]
It seems it might be just a `options` argument away, see https://github.com/websockets/ws/blob/master/doc/ws.md#new-wswebsocketaddress-protocols-options. In this line we pass no `options` https://github.com/maxogden/websocket-stream/blob/master/stream.js#L17.

I am ok for passing through the `options`, but nothing more. @mafintosh @maxogden what do you think?

**Comment by maxogden** [comment]
yea that sounds good to me

**Comment by mafintosh** [comment]
:+1:

**Comment by binarykitchen** [comment]
Ok, now that you have agreed on this, here a small PR https://github.com/maxogden/websocket-stream/pull/67

@mcollina If you dig deeper, it turns out that WebSocket.js already treats the protocols argument as options under some circumstances, see https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L49
