### ISSUE TITLE
Assumes it's a server?  broken as a browser client?

### ISSUE THREAD

**Issue by andywatts** [maxogden/websocket-stream#74]
index.js requires server.js
server.js creates a ws server instance.  This is undefined when in a browser.
server.js then tries to inherit prototypes from this undefined WebSocketServer.
This inherit throws an error.

test-client isn't capturing this.

**Comment by mcollina** [comment]
How are you building the browserify bundle for this library?

This is working fine for me in [mqtt](http://npm.im/mqtt).

**Comment by andywatts** [comment]
Using beefy, which in turn uses browserify.

Actually trying to update maxogden/voxel-client.
It's pinned to websocket-stream v0.0.5
Get the 'undefined' error when I update voxel-client to use websocket-stream v2.0.2

**Comment by andywatts** [comment]
Apologies.  This was due to old beefy/browserify
