### ISSUE TITLE
WebSocket.prototype.addEventListener is not a function in latest Chrome

### ISSUE THREAD

**Issue by tothandras** [maxogden/websocket-stream#87]
An error is thrown at [line 50 in stream.js](https://github.com/maxogden/websocket-stream/blob/master/stream.js#L50). 
```
> WebSocket.prototype.addEventListener
undefined
```
Chrome version: `50.0.2661.94`
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) `addEventListener` is not a function on WebSocket, although it still works in Chrome Canary, Mozilla and Safari.

**Comment by mcollina** [comment]
Would you like to send a PR to address this?

**Comment by tothandras** [comment]
Will do.

**Comment by mcollina** [comment]
@tothandras thanks!!

**Comment by tothandras** [comment]
Should it use `addEventListener` by default, or just replace those lines altogether?

**Comment by mcollina** [comment]
We need a solution that works across browsers and in node as well. Once this is achieved, I'm fine.

**Comment by tothandras** [comment]
I've done nothing, but it's there again:
```
> WebSocket.prototype.addEventListener
function addEventListener() { [native code] }
```
Same Chrome version...

**Comment by mcollina** [comment]
Weird, can we close then?

**Comment by tothandras** [comment]
I am not sure, the `addEventListener ` is not part of the WebSocket standard, so it can disappear anytime.

**Comment by mcollina** [comment]
I think you should bring this discussion to the ws module, and we'll follow
what they suggest.
I am against on having feature detection here (unless we have no
alternative).
Il giorno mar 3 mag 2016 alle 13:15 András Tóth <notifications@github.com>
ha scritto:

**Comment by tothandras** [comment]
I agree. Will you contact them?
(Fun fact: one of my coworker still doesn't have `WebSocket.prototype.addEventListener`.)

**Comment by tothandras** [comment]
Oh, I just reread your message, I will bring it up then. :)

**Comment by tothandras** [comment]
It's there, but I haven't noticed: https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L402-L484. I've updated the PR.
