### ISSUE TITLE
isn't an instance of stream.Readable

### ISSUE THREAD

**Issue by NodeGuy** [maxogden/websocket-stream#98]
Duplex streams in Node.js [inherit from `stream.Readable`](https://nodejs.org/dist/latest-v4.x/docs/api/stream.html#stream_class_stream_duplex_1):

> Since JavaScript doesn't have multiple prototypal inheritance, this class prototypally inherits from Readable, and then parasitically from Writable.

`websocket-stream` doesn't do this and I can't use it with generic functions that dispatch on type.

My desire is for `websocket-stream` to inherit from `stream.Readable` like duplex streams do in Node.js.

**Comment by mcollina** [comment]
I'm certain that any instance returned by `websocket-stream` is a duplex. Can you upload an example of what you are trying to achieve?

BTW, _desires_ have little room in open source.

**Comment by NodeGuy** [comment]
I solved my problem a different way so I don't need this anymore, thank you.

What are you saying, pull requests carry more water than desires?  ;-)
